### ISSUE TITLE
Feedback from dennispi@gmail.com on build #7: Email please?

### ISSUE THREAD

**Issue by SidBala** [iOSTestApps/2048#167]
Feedback from dennispi@gmail.com : Email please?

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/55b97bae9756d70100762e52/55bbbfb8435fbb01005a616b/1aca2d42-d2de-40b8-a3f6-73ca0c22e0cd.jpg" width="33%" height="33%" />

**Comment by rasharab** [comment]
S
